drop table if exists ENDPOINT_HIT;

create table if not exists ENDPOINT_HIT (
    id              BIGINT generated by default as identity,
    app             VARCHAR(256),
    uri             VARCHAR(512),
    ip              VARCHAR(64),
    created         TIMESTAMP WITHOUT TIME ZONE,
    constraint ENDPOINT_HIT_PK primary key (id)
);

CREATE INDEX idx_app on endpoint_hit (app);
CREATE INDEX idx_ip on endpoint_hit (ip);
CREATE INDEX idx_uri on endpoint_hit (uri);
CREATE INDEX idx_timestamp on endpoint_hit (created);
CREATE INDEX idx_uri_timestamp on endpoint_hit (uri, created);
CREATE INDEX idx_app_uri on endpoint_hit (app, uri);